### ISSUE TITLE
Support for chef-pulp cookbook

### ISSUE THREAD

**Issue by larsjuetten** [nkts/chef-pulp#1]
Hi,

my name is Lars and I was playing around with your chef-pulp cookbooks as we're going to use pulp-server in an automatted environment.
When using your cookbook I was stumbling over some issues (like the 'pulp-manage-db' has to be run as apache) and I was wondering, why you didn't continue your work on those.

Best regards,

   Lars

**Comment by nkts** [comment]
The main reason is I have implemented only what I needed. I'll have not touched this for a long time, will have a look soon.
